//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register
    {
        public tbl_Register()
        {
            this.Tbl_Attendance = new HashSet<Tbl_Attendance>();
            this.Tbl_Leaves = new HashSet<Tbl_Leaves>();
            this.Tbl_Payslips = new HashSet<Tbl_Payslips>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> MId { get; set; }
    
        public virtual ICollection<Tbl_Attendance> Tbl_Attendance { get; set; }
        public virtual ICollection<Tbl_Leaves> Tbl_Leaves { get; set; }
        public virtual Tbl_Manager Tbl_Manager { get; set; }
        public virtual ICollection<Tbl_Payslips> Tbl_Payslips { get; set; }
    }
}
