//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Attendance
    {
        public int AId { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> MID { get; set; }
        public string SickLeaves { get; set; }
        public string PrivilegeLeaves { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
    
        public virtual Tbl_Manager Tbl_Manager { get; set; }
        public virtual tbl_Register tbl_Register { get; set; }
    }
}
