//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Manager
    {
        public Tbl_Manager()
        {
            this.Tbl_Attendance = new HashSet<Tbl_Attendance>();
            this.Tbl_Leaves = new HashSet<Tbl_Leaves>();
            this.Tbl_Payslips = new HashSet<Tbl_Payslips>();
            this.tbl_Register = new HashSet<tbl_Register>();
        }
    
        public int Mid { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual ICollection<Tbl_Attendance> Tbl_Attendance { get; set; }
        public virtual ICollection<Tbl_Leaves> Tbl_Leaves { get; set; }
        public virtual ICollection<Tbl_Payslips> Tbl_Payslips { get; set; }
        public virtual ICollection<tbl_Register> tbl_Register { get; set; }
    }
}
